---

- name: Configure zabbix userparameters
  include_role:
    name: zabbix-agent
    tasks_from: types/user_parameter
  vars:
    zabbix_agent__userparameter:
      name: apt
      userparameters:
        - key: apt.updates
          command: >
            {%- if apt__use_cached_updates_list|bool -%}
            /bin/bash -c
            "test -f {{ apt__cached_updates_file }}
            && wc -l < {{ apt__cached_updates_file }}
            || echo -n 'ZBX_NOTSUPPORTED'"
            {%- else -%}
            /usr/bin/apt-get --just-print
            --option Debug::NoLocking=true upgrade --assume-no
            | grep --ignore-case --count --perl-regexp '^Inst((?!security).)*$'
            | tr -d '\n'
            {%- endif -%}
          comment: packages number that need normal updates
        - key: apt.security_updates
          command: >
            {% if apt__use_cached_updates_list|bool %}
            /bin/bash -c
            "test -f {{ apt__cached_security_updates_file }}
            && wc -l < {{ apt__cached_security_updates_file }}
            || echo -n 'ZBX_NOTSUPPORTED'"
            {% else %}
            /usr/bin/apt-get --just-print
            --option Debug::NoLocking=true upgrade --assume-no
            | grep --ignore-case --count '^inst.*security' | tr -d '\n'
            {% endif %}
          comment: packages number that need security updates
      state: present
  tags: ['apt', 'apt-monitoring']
