---

- name: Create apt directories
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - '{{ apt__configuration_directory }}'
    - '{{ apt__configuration_include_directory }}'
    - '{{ apt__preferences_directory }}'
    - '{{ apt__sources_list_directory }}'
    - '{{ apt__custom_scripts_directory }}'
    - '{{ apt__variable_directory }}'
    - '{{ apt__cache_directory }}'
    - '{{ apt__backup_directory }}'

- name: Install apt custom scripts
  template:
    src: '{{ item }}.j2'
    dest: '{{ apt__custom_scripts_directory }}/{{ item }}'
    owner: root
    group: root
    mode: 0755
  with_items:
    - update-packages-lists.sh

- name: Install apt configuration
  template:
    src: apt.conf.j2
    dest: '{{ apt__configuration_file }}'
    owner: root
    group: root
    mode: 0644

- name: Update apt listchanges configuration
  template:
    src: listchanges.conf.j2
    dest: '{{ apt__listchanges_configuration_file }}'
    owner: root
    group: root
    mode: 0644

- name:
  import_tasks: configure-settings.yml

- name:
  import_tasks: configure-keys.yml

- name:
  import_tasks: configure-repositories.yml

- name:
  import_tasks: configure-preferences.yml
