---

- name: Assert required variables
  assert:
    that:
      - apt__repositories|length > 0
      - apt__repositories is iterable
    msg: You must have at least one repository for this host

- name: Configure main sources list file
  template:
    src: sources.list.j2
    dest: '{{ apt__sources_list }}'
    owner: root
    group: root
    mode: 0644

- name: List installed repositories
  find:
    paths: '{{ apt__sources_list_directory }}'
    file_type: file
  register: _apt__installed_repositories_files

# purge feature

- name: Remove unknown installed repositories
  file:
    path: '{{ item }}'
    state: absent
  with_items: "\
    {% set to_remove = [] -%}
    {% set to_keep = apt__repositories|map(attribute='name')|list -%}
    {% for path in _apt__installed_repositories_files.files|map(attribute='path')|list -%}
    {%   if path|basename|replace('.list', '') not in to_keep -%}
    {%     set _ = to_remove.append(path) -%}
    {%   endif -%}
    {% endfor -%}
    {{ to_remove }}"
  when: apt__repositories_purge|bool

- name: Adding apt repository
  apt_repository:
    repo: '{{ item.repo }}'
    codename: '{{ item.codename|d(omit) }}'
    filename: '{{ item.name|d(omit) }}'
    update_cache: false
    state: "{{ item.state|d('present') }}"
  with_items: '{{ apt__repositories|list }}'
  notify: ['update-apt-package-cache']
