---

- name: Install apt preferences settings
  template:
    src: preferences.j2
    dest: '{{ apt__preferences }}'
    owner: root
    group: root
    mode: 0644

- name: List installed apt preferences
  find:
    paths: '{{ apt__preferences_directory }}'
    file_type: file
  register: _apt__installed_preferences_files

# purge feature

- name: List ansible managed apt preferences
  find:
    paths: '{{ apt__preferences_directory }}'
    file_type: file
    contains: '#{{ apt__ansible_managed_key }}'
  when: apt__preferences_purge|bool
  register: _apt__managed_preferences_files

- name: Remove unknown installed apt preferences
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    "{{ _apt__installed_preferences_files.files|map(attribute='path')
        |difference(_apt__managed_preferences_files.files|map(attribute='path'))|list }}"
  when: apt__preferences_purge|bool

- name: Create apt pinnings
  include_tasks: types/pin.yml
  vars:
    apt__pin: "{{ outer_item.value|combine({'name': outer_item.key}) }}"
  with_dict: '{{ apt__pins }}'
  loop_control:
    loop_var: outer_item
