---
- name: Create the directory for APT configuration
  file:
    path:  '{{ item }}'
    owner: root
    group: root
    mode:  0755
    state: directory
  with_items:
    - '{{ apt__conf_dir }}'
    - '{{ apt__include_conf_dir }}'
    - '{{ apt__sources_list_dir }}'

- name: Install apt configuration settings
  template:
    src:   '{{ item }}.j2'
    dest:  '{{ apt__include_conf_dir }}/{{ item }}'
    owner: root
    group: root
    mode:  0644
  with_items:
    - 01proxy
    - 02periodic
    - 15update-stamp
    - 20auto-upgrades
    - 50unattended-upgrades

- import_tasks: configure-keys.yml
- import_tasks: configure-repositories.yml
