---
# tasks file for apt

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: 'This module only works on Debian or derivatives like Ubuntu'
  when: ansible_os_family != 'Debian'

- import_tasks: install.yml
  tags: ['apt', 'apt-install']

- import_tasks: configure.yml
  tags: ['apt', 'apt-configure']

- include_tasks: facts.yml
  when: apt__facts|bool
  tags: ['apt', 'apt-facts']
