---

- name: Configure zabbix userparameters
  include_role:
    name: zabbix-common
    tasks_from: userparameter
  vars:
    zabbix_common__userparameter:
      name: apt
      userparameter:
        - key: apt.updates
          command: >
            {%- if apt__use_cached_updates_list|bool -%}
            /bin/bash -c "if [ -f {{ apt__cached_updates_file }} ]; then wc -l < {{ apt__cached_updates_file }}; else echo -n 'ZBX_NOTSUPPORTED'; fi"
            {%- else -%}
            /usr/bin/apt-get --just-print --option Debug::NoLocking=true upgrade --assume-no | grep --ignore-case --count --perl-regexp '^Inst((?!security).)*$' | tr -d '\n'
            {%- endif -%}
          comment: packages number that need normal updates
        - key: apt.security_updates
          command: >
            {% if apt__use_cached_updates_list|bool %}
            /bin/bash -c "if [ -f {{ apt__cached_security_updates_file }} ]; then wc -l < {{ apt__cached_security_updates_file }}; else echo -n 'ZBX_NOTSUPPORTED'; fi"
            {% else %}
            /usr/bin/apt-get --just-print --option Debug::NoLocking=true upgrade --assume-no | grep --ignore-case --count '^inst.*security' | tr -d '\n'
            {% endif %}
          comment: packages number that need security updates
      state: present
