---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: "Include turgon37.apt"
      include_role:
        name: "ansible-apt"
  vars:
    repositories:
      Debian:
          - name: debian
            repo: >
              deb 'http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free'
            codename: '{{ ansible_distribution_release }}'

    # Get host repository according to facts
    apt__repositories: '{{
      repositories[(
        ansible_lsb.id if ansible_lsb.id is defined else (
          ansible_distribution if ansible_distribution is defined else (
            ansible_os_family)
          )
        )]
      }}'
